// This file is auto-generated by @hey-api/openapi-ts

export type Body_Login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BuildingStructureTypeCreateIn = {
    name: string;
};

export type BuildingStructureTypePublicOut = {
    name: string;
    id: number;
};

export type BuildingStructureTypeUpdateIn = {
    name?: (string | null);
};

export type BuildingStructureTypesPublicOut = {
    data: Array<BuildingStructureTypePublicOut>;
    count: number;
};

export type BuildingTypeCreateIn = {
    name: string;
};

export type BuildingTypePublicOut = {
    name: string;
    id: number;
};

export type BuildingTypeUpdateIn = {
    name?: (string | null);
};

export type BuildingTypesPublicOut = {
    data: Array<BuildingTypePublicOut>;
    count: number;
};

export type ContractPaymentCreateIn = {
    payment_date: string;
    amount: number;
    processed_by_id: number;
    notes?: (string | null);
    project_payout_id: number;
};

export type ContractPaymentPayout = {
    project_payout_id: number;
    contract_payment_id: number;
    employee_id: number;
    employee_payout_amount: number;
    id?: number;
};

export type ContractPaymentPublicOut = {
    payment_date: string;
    amount: number;
    processed_by_id: number;
    notes?: (string | null);
    id: number;
    contract_payment_payouts?: (Array<ContractPaymentPayout> | null);
    paid_ratio: number;
    project_id: number;
    project_payout_id: number;
    payout_amount: number;
};

export type ContractPaymentUpdateIn = {
    payment_date?: (string | null);
    amount?: (number | null);
    processed_by_id?: (number | null);
    notes?: (string | null);
};

export type ContractPaymentsPublicOut = {
    data: Array<ContractPaymentPublicOut>;
    count: number;
};

export type DepartmentPayoutRatioPublicOut = {
    project_class_id: number;
    project_rate_adjustment_class_id: number;
    pm_ratio: number;
    arch_ratio: number;
    struct_ratio: number;
    plumbing_ratio: number;
    electrical_ratio: number;
    hvac_ratio: number;
    low_voltage_ratio: number;
    id: number;
    modified_at: string;
};

/**
 * 除了project_class_id和project_rate_adjustment_class_id, 其他字段都允许修改
 */
export type DepartmentPayoutRatioUpdateIn = {
    project_class_id: number;
    project_rate_adjustment_class_id: number;
    pm_ratio?: (number | null);
    arch_ratio?: (number | null);
    struct_ratio?: (number | null);
    plumbing_ratio?: (number | null);
    electrical_ratio?: (number | null);
    hvac_ratio?: (number | null);
    low_voltage_ratio?: (number | null);
    modified_at?: string;
};

export type DepartmentPayoutRatiosPublicOut = {
    data: Array<DepartmentPayoutRatioPublicOut>;
    count: number;
};

export type DepartmentPublicOut = {
    name: string;
    description?: (string | null);
    id: number;
};

export type DepartmentsPublicOut = {
    data: Array<DepartmentPublicOut>;
    count: number;
};

export type EmployStatusCreateIn = {
    name: string;
    description?: (string | null);
};

export type EmployStatusPublicOut = {
    name: string;
    description?: (string | null);
    id: number;
};

export type EmployStatusUpdateIn = {
    name?: (string | null);
    description?: (string | null);
};

export type EmployStatusesPublicOut = {
    data: Array<EmployStatusPublicOut>;
    count: number;
};

export type EmployeeCreateIn = {
    name: string;
    gov_id?: (string | null);
    gender?: (string | null);
    department_id?: (number | null);
    work_location_id?: (number | null);
    employee_title_id?: (number | null);
    professional_title_id?: (number | null);
    employ_status_id: number;
    birth_date?: (string | null);
    initial?: (string | null);
    pinyin?: (string | null);
};

export type EmployeePublicOut = {
    name: string;
    gov_id?: (string | null);
    gender?: (string | null);
    department_id?: (number | null);
    work_location_id?: (number | null);
    employee_title_id?: (number | null);
    professional_title_id?: (number | null);
    employ_status_id: number;
    birth_date?: (string | null);
    initial: string;
    pinyin: string;
    id: number;
};

export type EmployeeTitleCreateIn = {
    name: string;
    description?: (string | null);
};

export type EmployeeTitlePublicOut = {
    name: string;
    description?: (string | null);
    id: number;
};

export type EmployeeTitleUpdateIn = {
    name?: (string | null);
    description?: (string | null);
};

export type EmployeeTitlesPublicOut = {
    data: Array<EmployeeTitlePublicOut>;
    count: number;
};

export type EmployeeUpdateIn = {
    name?: (string | null);
    gov_id?: (string | null);
    gender?: (string | null);
    department_id?: (number | null);
    work_location_id?: (number | null);
    employee_title_id?: (number | null);
    professional_title_id?: (number | null);
    employ_status_id?: (number | null);
    birth_date?: (string | null);
    initial?: (string | null);
    pinyin?: (string | null);
};

export type EmployeesPublicOut = {
    data: Array<EmployeePublicOut>;
    count: number;
};

export type ErrorResponse = {
    detail: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreateIn = {
    title: string;
    description?: (string | null);
};

export type ItemPublicOut = {
    title: string;
    description?: (string | null);
    id: number;
    owner_id: number;
};

export type ItemUpdateIn = {
    title?: (string | null);
    description?: (string | null);
};

export type ItemsPublicOut = {
    data: Array<ItemPublicOut>;
    count: number;
};

/**
 * 除hidden外必须提供所有字段
 */
export type JobPayoutRatioProfileCreateIn = {
    name: string;
    hidden?: (boolean | null);
    pm_ratio: number;
    pm_assistant_ratio: number;
    arch_pm_ratio: number;
    arch_pm_assistant_ratio: number;
    arch_designer_ratio: number;
    arch_drafter_ratio: number;
    arch_design_post_service_ratio: number;
    arch_proofreader_ratio: number;
    arch_reviewer_ratio: number;
    arch_approver_ratio: number;
    struct_pm_ratio: number;
    struct_pm_assistant_ratio: number;
    struct_designer_ratio: number;
    struct_drafter_ratio: number;
    struct_design_post_service_ratio: number;
    struct_proofreader_ratio: number;
    struct_reviewer_ratio: number;
    struct_approver_ratio: number;
    plumbing_pm_ratio: number;
    plumbing_pm_assistant_ratio: number;
    plumbing_designer_ratio: number;
    plumbing_drafter_ratio: number;
    plumbing_design_post_service_ratio: number;
    plumbing_proofreader_ratio: number;
    plumbing_reviewer_ratio: number;
    plumbing_approver_ratio: number;
    electrical_pm_ratio: number;
    electrical_pm_assistant_ratio: number;
    electrical_designer_ratio: number;
    electrical_drafter_ratio: number;
    electrical_design_post_service_ratio: number;
    electrical_reviewer_ratio: number;
    electrical_proofreader_ratio: number;
    electrical_approver_ratio: number;
    hvac_pm_ratio: number;
    hvac_pm_assistant_ratio: number;
    hvac_designer_ratio: number;
    hvac_drafter_ratio: number;
    hvac_design_post_service_ratio: number;
    hvac_proofreader_ratio: number;
    hvac_reviewer_ratio: number;
    hvac_approver_ratio: number;
    low_voltage_pm_ratio: number;
    low_voltage_pm_assistant_ratio: number;
    low_voltage_designer_ratio: number;
    low_voltage_drafter_ratio: number;
    low_voltage_design_post_service_ratio: number;
    low_voltage_proofreader_ratio: number;
    low_voltage_reviewer_ratio: number;
    low_voltage_approver_ratio: number;
};

export type JobPayoutRatioProfilePublicOut = {
    name: string;
    hidden: boolean;
    pm_ratio: number;
    pm_assistant_ratio: number;
    arch_pm_ratio: number;
    arch_pm_assistant_ratio: number;
    arch_designer_ratio: number;
    arch_drafter_ratio: number;
    arch_design_post_service_ratio: number;
    arch_proofreader_ratio: number;
    arch_reviewer_ratio: number;
    arch_approver_ratio: number;
    struct_pm_ratio: number;
    struct_pm_assistant_ratio: number;
    struct_designer_ratio: number;
    struct_drafter_ratio: number;
    struct_design_post_service_ratio: number;
    struct_proofreader_ratio: number;
    struct_reviewer_ratio: number;
    struct_approver_ratio: number;
    plumbing_pm_ratio: number;
    plumbing_pm_assistant_ratio: number;
    plumbing_designer_ratio: number;
    plumbing_drafter_ratio: number;
    plumbing_design_post_service_ratio: number;
    plumbing_proofreader_ratio: number;
    plumbing_reviewer_ratio: number;
    plumbing_approver_ratio: number;
    electrical_pm_ratio: number;
    electrical_pm_assistant_ratio: number;
    electrical_designer_ratio: number;
    electrical_drafter_ratio: number;
    electrical_design_post_service_ratio: number;
    electrical_reviewer_ratio: number;
    electrical_proofreader_ratio: number;
    electrical_approver_ratio: number;
    hvac_pm_ratio: number;
    hvac_pm_assistant_ratio: number;
    hvac_designer_ratio: number;
    hvac_drafter_ratio: number;
    hvac_design_post_service_ratio: number;
    hvac_proofreader_ratio: number;
    hvac_reviewer_ratio: number;
    hvac_approver_ratio: number;
    low_voltage_pm_ratio: number;
    low_voltage_pm_assistant_ratio: number;
    low_voltage_designer_ratio: number;
    low_voltage_drafter_ratio: number;
    low_voltage_design_post_service_ratio: number;
    low_voltage_proofreader_ratio: number;
    low_voltage_reviewer_ratio: number;
    low_voltage_approver_ratio: number;
    id: number;
    updated_at: string;
    is_in_use: boolean;
};

/**
 * 除了name和hidden, 其他字段都不允许修改
 */
export type JobPayoutRatioProfileUpdateIn = {
    name?: (string | null);
    hidden?: (boolean | null);
    pm_ratio?: (number | null);
    pm_assistant_ratio?: (number | null);
    arch_pm_ratio?: (number | null);
    arch_pm_assistant_ratio?: (number | null);
    arch_designer_ratio?: (number | null);
    arch_drafter_ratio?: (number | null);
    arch_design_post_service_ratio?: (number | null);
    arch_proofreader_ratio?: (number | null);
    arch_reviewer_ratio?: (number | null);
    arch_approver_ratio?: (number | null);
    struct_pm_ratio?: (number | null);
    struct_pm_assistant_ratio?: (number | null);
    struct_designer_ratio?: (number | null);
    struct_drafter_ratio?: (number | null);
    struct_design_post_service_ratio?: (number | null);
    struct_proofreader_ratio?: (number | null);
    struct_reviewer_ratio?: (number | null);
    struct_approver_ratio?: (number | null);
    plumbing_pm_ratio?: (number | null);
    plumbing_pm_assistant_ratio?: (number | null);
    plumbing_designer_ratio?: (number | null);
    plumbing_drafter_ratio?: (number | null);
    plumbing_design_post_service_ratio?: (number | null);
    plumbing_proofreader_ratio?: (number | null);
    plumbing_reviewer_ratio?: (number | null);
    plumbing_approver_ratio?: (number | null);
    electrical_pm_ratio?: (number | null);
    electrical_pm_assistant_ratio?: (number | null);
    electrical_designer_ratio?: (number | null);
    electrical_drafter_ratio?: (number | null);
    electrical_design_post_service_ratio?: (number | null);
    electrical_reviewer_ratio?: (number | null);
    electrical_proofreader_ratio?: (number | null);
    electrical_approver_ratio?: (number | null);
    hvac_pm_ratio?: (number | null);
    hvac_pm_assistant_ratio?: (number | null);
    hvac_designer_ratio?: (number | null);
    hvac_drafter_ratio?: (number | null);
    hvac_design_post_service_ratio?: (number | null);
    hvac_proofreader_ratio?: (number | null);
    hvac_reviewer_ratio?: (number | null);
    hvac_approver_ratio?: (number | null);
    low_voltage_pm_ratio?: (number | null);
    low_voltage_pm_assistant_ratio?: (number | null);
    low_voltage_designer_ratio?: (number | null);
    low_voltage_drafter_ratio?: (number | null);
    low_voltage_design_post_service_ratio?: (number | null);
    low_voltage_proofreader_ratio?: (number | null);
    low_voltage_reviewer_ratio?: (number | null);
    low_voltage_approver_ratio?: (number | null);
};

export type JobPayoutRatioProfilesPublicOut = {
    data: Array<JobPayoutRatioProfilePublicOut>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ProdValueCalcRatioCreateIn = {
    name: string;
    ratio: number;
    default?: boolean;
};

export type ProdValueCalcRatioPublicOut = {
    name: string;
    ratio: number;
    id: number;
    default: boolean;
};

export type ProdValueCalcRatioUpdateIn = {
    name?: (string | null);
    ratio?: (number | null);
    default?: (boolean | null);
};

export type ProdValueCalcRatiosPublicOut = {
    data: Array<ProdValueCalcRatioPublicOut>;
    count: number;
};

export type ProfessionalTitleCreateIn = {
    name: string;
    description?: (string | null);
};

export type ProfessionalTitlePublicOut = {
    name: string;
    description?: (string | null);
    id: number;
};

export type ProfessionalTitleUpdateIn = {
    name?: (string | null);
    description?: (string | null);
};

export type ProfessionalTitlesPublicOut = {
    data: Array<ProfessionalTitlePublicOut>;
    count: number;
};

export type ProjectClassCreateIn = {
    name: string;
};

export type ProjectClassPublicOut = {
    name: string;
    id: number;
};

export type ProjectClassUpdateIn = {
    name?: (string | null);
};

export type ProjectClassesPublicOut = {
    data: Array<ProjectClassPublicOut>;
    count: number;
};

export type ProjectCreateIn = {
    project_code: string;
    name: string;
    project_year: number;
    project_type_id: number;
    building_type_id: number;
    project_task_type_id: number;
    project_class_id: number;
    building_structure_type_id: number;
    project_rate_adjustment_class_id: number;
    quality_ratio_class_id: number;
    project_area?: (number | null);
    project_construction_cost?: (number | null);
    calculated_employee_payout: number;
    project_contract_value: number;
    notes?: (string | null);
};

export type ProjectPayoutCreateIn = {
    project_id: number;
    pm_id?: (number | null);
    pm_payout?: (number | null);
    pm_assistant_id?: (number | null);
    pm_assistant_payout?: (number | null);
    arch_pm_id?: (number | null);
    arch_pm_payout?: (number | null);
    arch_pm_assistant_id?: (number | null);
    arch_pm_assistant_payout?: (number | null);
    arch_designer_id?: (number | null);
    arch_designer_payout?: (number | null);
    arch_drafter_id?: (number | null);
    arch_drafter_payout?: (number | null);
    arch_design_post_service_id?: (number | null);
    arch_design_post_service_payout?: (number | null);
    arch_proofreader_id?: (number | null);
    arch_proofreader_payout?: (number | null);
    arch_reviewer_id?: (number | null);
    arch_reviewer_payout?: (number | null);
    arch_approver_id?: (number | null);
    arch_approver_payout?: (number | null);
    struct_pm_id?: (number | null);
    struct_pm_payout?: (number | null);
    struct_pm_assistant_id?: (number | null);
    struct_pm_assistant_payout?: (number | null);
    struct_designer_id?: (number | null);
    struct_designer_payout?: (number | null);
    struct_drafter_id?: (number | null);
    struct_drafter_payout?: (number | null);
    struct_design_post_service_id?: (number | null);
    struct_design_post_service_payout?: (number | null);
    struct_proofreader_id?: (number | null);
    struct_proofreader_payout?: (number | null);
    struct_reviewer_id?: (number | null);
    struct_reviewer_payout?: (number | null);
    struct_approver_id?: (number | null);
    struct_approver_payout?: (number | null);
    plumbing_pm_id?: (number | null);
    plumbing_pm_payout?: (number | null);
    plumbing_pm_assistant_id?: (number | null);
    plumbing_pm_assistant_payout?: (number | null);
    plumbing_designer_id?: (number | null);
    plumbing_designer_payout?: (number | null);
    plumbing_drafter_id?: (number | null);
    plumbing_drafter_payout?: (number | null);
    plumbing_design_post_service_id?: (number | null);
    plumbing_design_post_service_payout?: (number | null);
    plumbing_proofreader_id?: (number | null);
    plumbing_proofreader_payout?: (number | null);
    plumbing_reviewer_id?: (number | null);
    plumbing_reviewer_payout?: (number | null);
    plumbing_approver_id?: (number | null);
    plumbing_approver_payout?: (number | null);
    electrical_pm_id?: (number | null);
    electrical_pm_payout?: (number | null);
    electrical_pm_assistant_id?: (number | null);
    electrical_pm_assistant_payout?: (number | null);
    electrical_designer_id?: (number | null);
    electrical_designer_payout?: (number | null);
    electrical_drafter_id?: (number | null);
    electrical_drafter_payout?: (number | null);
    electrical_design_post_service_id?: (number | null);
    electrical_design_post_service_payout?: (number | null);
    electrical_reviewer_id?: (number | null);
    electrical_reviewer_payout?: (number | null);
    electrical_proofreader_id?: (number | null);
    electrical_proofreader_payout?: (number | null);
    electrical_approver_id?: (number | null);
    electrical_approver_payout?: (number | null);
    hvac_pm_id?: (number | null);
    hvac_pm_payout?: (number | null);
    hvac_pm_assistant_id?: (number | null);
    hvac_pm_assistant_payout?: (number | null);
    hvac_designer_id?: (number | null);
    hvac_designer_payout?: (number | null);
    hvac_drafter_id?: (number | null);
    hvac_drafter_payout?: (number | null);
    hvac_design_post_service_id?: (number | null);
    hvac_design_post_service_payout?: (number | null);
    hvac_proofreader_id?: (number | null);
    hvac_proofreader_payout?: (number | null);
    hvac_reviewer_id?: (number | null);
    hvac_reviewer_payout?: (number | null);
    hvac_approver_id?: (number | null);
    hvac_approver_payout?: (number | null);
    low_voltage_pm_id?: (number | null);
    low_voltage_pm_payout?: (number | null);
    low_voltage_pm_assistant_id?: (number | null);
    low_voltage_pm_assistant_payout?: (number | null);
    low_voltage_designer_id?: (number | null);
    low_voltage_designer_payout?: (number | null);
    low_voltage_drafter_id?: (number | null);
    low_voltage_drafter_payout?: (number | null);
    low_voltage_design_post_service_id?: (number | null);
    low_voltage_design_post_service_payout?: (number | null);
    low_voltage_proofreader_id?: (number | null);
    low_voltage_proofreader_payout?: (number | null);
    low_voltage_reviewer_id?: (number | null);
    low_voltage_reviewer_payout?: (number | null);
    low_voltage_approver_id?: (number | null);
    low_voltage_approver_payout?: (number | null);
    manually_modified?: boolean;
    job_payout_ratio_profile_id: number;
    department_payout_ratio_id?: (number | null);
};

export type ProjectPayoutPublicOut = {
    project_id: number;
    pm_id?: (number | null);
    pm_payout?: (number | null);
    pm_assistant_id?: (number | null);
    pm_assistant_payout?: (number | null);
    arch_pm_id?: (number | null);
    arch_pm_payout?: (number | null);
    arch_pm_assistant_id?: (number | null);
    arch_pm_assistant_payout?: (number | null);
    arch_designer_id?: (number | null);
    arch_designer_payout?: (number | null);
    arch_drafter_id?: (number | null);
    arch_drafter_payout?: (number | null);
    arch_design_post_service_id?: (number | null);
    arch_design_post_service_payout?: (number | null);
    arch_proofreader_id?: (number | null);
    arch_proofreader_payout?: (number | null);
    arch_reviewer_id?: (number | null);
    arch_reviewer_payout?: (number | null);
    arch_approver_id?: (number | null);
    arch_approver_payout?: (number | null);
    struct_pm_id?: (number | null);
    struct_pm_payout?: (number | null);
    struct_pm_assistant_id?: (number | null);
    struct_pm_assistant_payout?: (number | null);
    struct_designer_id?: (number | null);
    struct_designer_payout?: (number | null);
    struct_drafter_id?: (number | null);
    struct_drafter_payout?: (number | null);
    struct_design_post_service_id?: (number | null);
    struct_design_post_service_payout?: (number | null);
    struct_proofreader_id?: (number | null);
    struct_proofreader_payout?: (number | null);
    struct_reviewer_id?: (number | null);
    struct_reviewer_payout?: (number | null);
    struct_approver_id?: (number | null);
    struct_approver_payout?: (number | null);
    plumbing_pm_id?: (number | null);
    plumbing_pm_payout?: (number | null);
    plumbing_pm_assistant_id?: (number | null);
    plumbing_pm_assistant_payout?: (number | null);
    plumbing_designer_id?: (number | null);
    plumbing_designer_payout?: (number | null);
    plumbing_drafter_id?: (number | null);
    plumbing_drafter_payout?: (number | null);
    plumbing_design_post_service_id?: (number | null);
    plumbing_design_post_service_payout?: (number | null);
    plumbing_proofreader_id?: (number | null);
    plumbing_proofreader_payout?: (number | null);
    plumbing_reviewer_id?: (number | null);
    plumbing_reviewer_payout?: (number | null);
    plumbing_approver_id?: (number | null);
    plumbing_approver_payout?: (number | null);
    electrical_pm_id?: (number | null);
    electrical_pm_payout?: (number | null);
    electrical_pm_assistant_id?: (number | null);
    electrical_pm_assistant_payout?: (number | null);
    electrical_designer_id?: (number | null);
    electrical_designer_payout?: (number | null);
    electrical_drafter_id?: (number | null);
    electrical_drafter_payout?: (number | null);
    electrical_design_post_service_id?: (number | null);
    electrical_design_post_service_payout?: (number | null);
    electrical_reviewer_id?: (number | null);
    electrical_reviewer_payout?: (number | null);
    electrical_proofreader_id?: (number | null);
    electrical_proofreader_payout?: (number | null);
    electrical_approver_id?: (number | null);
    electrical_approver_payout?: (number | null);
    hvac_pm_id?: (number | null);
    hvac_pm_payout?: (number | null);
    hvac_pm_assistant_id?: (number | null);
    hvac_pm_assistant_payout?: (number | null);
    hvac_designer_id?: (number | null);
    hvac_designer_payout?: (number | null);
    hvac_drafter_id?: (number | null);
    hvac_drafter_payout?: (number | null);
    hvac_design_post_service_id?: (number | null);
    hvac_design_post_service_payout?: (number | null);
    hvac_proofreader_id?: (number | null);
    hvac_proofreader_payout?: (number | null);
    hvac_reviewer_id?: (number | null);
    hvac_reviewer_payout?: (number | null);
    hvac_approver_id?: (number | null);
    hvac_approver_payout?: (number | null);
    low_voltage_pm_id?: (number | null);
    low_voltage_pm_payout?: (number | null);
    low_voltage_pm_assistant_id?: (number | null);
    low_voltage_pm_assistant_payout?: (number | null);
    low_voltage_designer_id?: (number | null);
    low_voltage_designer_payout?: (number | null);
    low_voltage_drafter_id?: (number | null);
    low_voltage_drafter_payout?: (number | null);
    low_voltage_design_post_service_id?: (number | null);
    low_voltage_design_post_service_payout?: (number | null);
    low_voltage_proofreader_id?: (number | null);
    low_voltage_proofreader_payout?: (number | null);
    low_voltage_reviewer_id?: (number | null);
    low_voltage_reviewer_payout?: (number | null);
    low_voltage_approver_id?: (number | null);
    low_voltage_approver_payout?: (number | null);
    id: number;
    created_at: string;
    calculation_updated_at: string;
    people_updated_at: string;
    contract_payment_payout_started: boolean;
    update_required_project_updated: boolean;
    department_payout_ratio_used_outdated: boolean;
    job_payout_ratio_profile_used_outdated: boolean;
};

export type ProjectPayoutUpdateIn = {
    project_id: null;
    pm_id?: (number | null);
    pm_payout?: (number | null);
    pm_assistant_id?: (number | null);
    pm_assistant_payout?: (number | null);
    arch_pm_id?: (number | null);
    arch_pm_payout?: (number | null);
    arch_pm_assistant_id?: (number | null);
    arch_pm_assistant_payout?: (number | null);
    arch_designer_id?: (number | null);
    arch_designer_payout?: (number | null);
    arch_drafter_id?: (number | null);
    arch_drafter_payout?: (number | null);
    arch_design_post_service_id?: (number | null);
    arch_design_post_service_payout?: (number | null);
    arch_proofreader_id?: (number | null);
    arch_proofreader_payout?: (number | null);
    arch_reviewer_id?: (number | null);
    arch_reviewer_payout?: (number | null);
    arch_approver_id?: (number | null);
    arch_approver_payout?: (number | null);
    struct_pm_id?: (number | null);
    struct_pm_payout?: (number | null);
    struct_pm_assistant_id?: (number | null);
    struct_pm_assistant_payout?: (number | null);
    struct_designer_id?: (number | null);
    struct_designer_payout?: (number | null);
    struct_drafter_id?: (number | null);
    struct_drafter_payout?: (number | null);
    struct_design_post_service_id?: (number | null);
    struct_design_post_service_payout?: (number | null);
    struct_proofreader_id?: (number | null);
    struct_proofreader_payout?: (number | null);
    struct_reviewer_id?: (number | null);
    struct_reviewer_payout?: (number | null);
    struct_approver_id?: (number | null);
    struct_approver_payout?: (number | null);
    plumbing_pm_id?: (number | null);
    plumbing_pm_payout?: (number | null);
    plumbing_pm_assistant_id?: (number | null);
    plumbing_pm_assistant_payout?: (number | null);
    plumbing_designer_id?: (number | null);
    plumbing_designer_payout?: (number | null);
    plumbing_drafter_id?: (number | null);
    plumbing_drafter_payout?: (number | null);
    plumbing_design_post_service_id?: (number | null);
    plumbing_design_post_service_payout?: (number | null);
    plumbing_proofreader_id?: (number | null);
    plumbing_proofreader_payout?: (number | null);
    plumbing_reviewer_id?: (number | null);
    plumbing_reviewer_payout?: (number | null);
    plumbing_approver_id?: (number | null);
    plumbing_approver_payout?: (number | null);
    electrical_pm_id?: (number | null);
    electrical_pm_payout?: (number | null);
    electrical_pm_assistant_id?: (number | null);
    electrical_pm_assistant_payout?: (number | null);
    electrical_designer_id?: (number | null);
    electrical_designer_payout?: (number | null);
    electrical_drafter_id?: (number | null);
    electrical_drafter_payout?: (number | null);
    electrical_design_post_service_id?: (number | null);
    electrical_design_post_service_payout?: (number | null);
    electrical_reviewer_id?: (number | null);
    electrical_reviewer_payout?: (number | null);
    electrical_proofreader_id?: (number | null);
    electrical_proofreader_payout?: (number | null);
    electrical_approver_id?: (number | null);
    electrical_approver_payout?: (number | null);
    hvac_pm_id?: (number | null);
    hvac_pm_payout?: (number | null);
    hvac_pm_assistant_id?: (number | null);
    hvac_pm_assistant_payout?: (number | null);
    hvac_designer_id?: (number | null);
    hvac_designer_payout?: (number | null);
    hvac_drafter_id?: (number | null);
    hvac_drafter_payout?: (number | null);
    hvac_design_post_service_id?: (number | null);
    hvac_design_post_service_payout?: (number | null);
    hvac_proofreader_id?: (number | null);
    hvac_proofreader_payout?: (number | null);
    hvac_reviewer_id?: (number | null);
    hvac_reviewer_payout?: (number | null);
    hvac_approver_id?: (number | null);
    hvac_approver_payout?: (number | null);
    low_voltage_pm_id?: (number | null);
    low_voltage_pm_payout?: (number | null);
    low_voltage_pm_assistant_id?: (number | null);
    low_voltage_pm_assistant_payout?: (number | null);
    low_voltage_designer_id?: (number | null);
    low_voltage_designer_payout?: (number | null);
    low_voltage_drafter_id?: (number | null);
    low_voltage_drafter_payout?: (number | null);
    low_voltage_design_post_service_id?: (number | null);
    low_voltage_design_post_service_payout?: (number | null);
    low_voltage_proofreader_id?: (number | null);
    low_voltage_proofreader_payout?: (number | null);
    low_voltage_reviewer_id?: (number | null);
    low_voltage_reviewer_payout?: (number | null);
    low_voltage_approver_id?: (number | null);
    low_voltage_approver_payout?: (number | null);
};

export type ProjectPayoutsPublicOut = {
    data: Array<ProjectPayoutPublicOut>;
    count: number;
};

export type ProjectPublicOut = {
    project_code: string;
    name: string;
    project_year: number;
    project_type_id: number;
    building_type_id: number;
    project_task_type_id: number;
    project_class_id: number;
    building_structure_type_id: number;
    project_rate_adjustment_class_id: number;
    quality_ratio_class_id: number;
    project_area?: (number | null);
    project_construction_cost?: (number | null);
    calculated_employee_payout: number;
    project_contract_value: number;
    notes?: (string | null);
    id: number;
    date_added: string;
    date_modified: string;
    project_payout?: (ProjectPayoutPublicOut | null);
};

export type ProjectRateAdjustmentClassCreateIn = {
    name: string;
};

export type ProjectRateAdjustmentClassPublicOut = {
    name: string;
    id: number;
};

export type ProjectRateAdjustmentClassUpdateIn = {
    name?: (string | null);
};

export type ProjectRateAdjustmentClassesPublicOut = {
    data: Array<ProjectRateAdjustmentClassPublicOut>;
    count: number;
};

export type ProjectTaskTypeCreateIn = {
    name: string;
};

export type ProjectTaskTypePublicOut = {
    name: string;
    id: number;
};

export type ProjectTaskTypeUpdateIn = {
    name?: (string | null);
};

export type ProjectTaskTypesPublicOut = {
    data: Array<ProjectTaskTypePublicOut>;
    count: number;
};

export type ProjectTypeCreateIn = {
    name: string;
    building_type_id: number;
    project_class_id: number;
    description?: (string | null);
};

export type ProjectTypePublicOut = {
    name: string;
    building_type_id: number;
    project_class_id: number;
    description?: (string | null);
    id: number;
};

export type ProjectTypeUpdateIn = {
    name?: (string | null);
    building_type_id?: (number | null);
    project_class_id?: (number | null);
    description?: (string | null);
};

export type ProjectTypesPublicOut = {
    data: Array<ProjectTypePublicOut>;
    count: number;
};

export type ProjectUpdateIn = {
    project_code?: (string | null);
    name?: (string | null);
    project_year?: (number | null);
    project_type_id?: (number | null);
    building_type_id?: (number | null);
    project_task_type_id?: (number | null);
    project_class_id?: (number | null);
    building_structure_type_id?: (number | null);
    project_rate_adjustment_class_id?: (number | null);
    quality_ratio_class_id?: (number | null);
    project_area?: (number | null);
    project_construction_cost?: (number | null);
    calculated_employee_payout?: (number | null);
    project_contract_value: number;
    notes?: (string | null);
};

export type ProjectsPublicOut = {
    data: Array<ProjectPublicOut>;
    count: number;
};

export type QualityRatioClassCreateIn = {
    name: string;
    ratio: number;
};

export type QualityRatioClassPublicOut = {
    name: string;
    ratio: number;
    id: number;
};

export type QualityRatioClassUpdateIn = {
    name?: (string | null);
    ratio?: (number | null);
};

export type QualityRatioClassesPublicOut = {
    data: Array<QualityRatioClassPublicOut>;
    count: number;
};

export type SortDirection = 'asc' | 'desc';

export const SortDirection = {
    ASC: 'asc',
    DESC: 'desc'
} as const;

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password_reset_by_admin?: boolean;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password_reset_by_admin?: boolean;
    id: number;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password_reset_by_admin?: boolean;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WorkLocationCreateIn = {
    name: string;
    description?: (string | null);
};

export type WorkLocationPublicOut = {
    name: string;
    description?: (string | null);
    id: number;
};

export type WorkLocationUpdateIn = {
    name?: (string | null);
    description?: (string | null);
};

export type WorkLocationsPublicOut = {
    data: Array<WorkLocationPublicOut>;
    count: number;
};

export type LoginAccessTokenData = {
    body: Body_Login_login_access_token;
};

export type LoginAccessTokenResponse = (Token);

export type LoginAccessTokenError = (HTTPValidationError);

export type TestTokenResponse = (UserPublic);

export type TestTokenError = unknown;

export type RefreshTokenResponse = (Token);

export type RefreshTokenError = unknown;

export type RecoverPasswordData = {
    path: {
        email: string;
    };
};

export type RecoverPasswordResponse = (Message);

export type RecoverPasswordError = (HTTPValidationError);

export type ResetPasswordData = {
    body: NewPassword;
};

export type ResetPasswordResponse = (Message);

export type ResetPasswordError = (HTTPValidationError);

export type RecoverPasswordHtmlContentData = {
    path: {
        email: string;
    };
};

export type RecoverPasswordHtmlContentResponse = (string);

export type RecoverPasswordHtmlContentError = (HTTPValidationError);

export type ReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadUsersResponse = (UsersPublic);

export type ReadUsersError = (HTTPValidationError);

export type CreateUserData = {
    body: UserCreate;
};

export type CreateUserResponse = (UserPublic);

export type CreateUserError = (HTTPValidationError);

export type ReadUserMeResponse = (UserPublic);

export type ReadUserMeError = unknown;

export type DeleteUserMeResponse = (Message);

export type DeleteUserMeError = unknown;

export type UpdateUserMeData = {
    body: UserUpdateMe;
};

export type UpdateUserMeResponse = (UserPublic);

export type UpdateUserMeError = (HTTPValidationError);

export type UpdatePasswordMeData = {
    body: UpdatePassword;
};

export type UpdatePasswordMeResponse = (Message);

export type UpdatePasswordMeError = (HTTPValidationError);

export type RegisterUserData = {
    body: UserRegister;
};

export type RegisterUserResponse = (UserPublic);

export type RegisterUserError = (HTTPValidationError);

export type ReadUserByIdData = {
    path: {
        user_id: number;
    };
};

export type ReadUserByIdResponse = (UserPublic);

export type ReadUserByIdError = (HTTPValidationError);

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: number;
    };
};

export type UpdateUserResponse = (UserPublic);

export type UpdateUserError = (HTTPValidationError);

export type DeleteUserData = {
    path: {
        user_id: number;
    };
};

export type DeleteUserResponse = (Message);

export type DeleteUserError = (HTTPValidationError);

export type AdminResetPasswordData = {
    path: {
        user_id: number;
    };
};

export type AdminResetPasswordResponse = (Message);

export type AdminResetPasswordError = (HTTPValidationError);

export type GetAndFilterProjectsData = {
    query?: {
        building_structure_type_id?: (number | null);
        building_type_id?: (number | null);
        calculated_employee_payout_max?: (number | null);
        calculated_employee_payout_min?: (number | null);
        date_added_from?: (string | null);
        date_added_to?: (string | null);
        date_modified_from?: (string | null);
        date_modified_to?: (string | null);
        id?: (number | null);
        limit?: number;
        name?: (string | null);
        project_area_max?: (number | null);
        project_area_min?: (number | null);
        project_class_id?: (number | null);
        project_code?: (string | null);
        project_construction_cost_max?: (number | null);
        project_construction_cost_min?: (number | null);
        project_contract_value_max?: (number | null);
        project_contract_value_min?: (number | null);
        project_rate_adjustment_class_id?: (number | null);
        project_task_type_id?: (number | null);
        project_type_id?: (number | null);
        project_year?: (number | null);
        quality_ratio_class_id?: (number | null);
        skip?: number;
        sort_by?: (string | null);
        sort_direction?: SortDirection;
    };
};

export type GetAndFilterProjectsResponse = (ProjectsPublicOut);

export type GetAndFilterProjectsError = (ErrorResponse | HTTPValidationError);

export type CreateProjectData = {
    body: ProjectCreateIn;
};

export type CreateProjectResponse = (ProjectPublicOut);

export type CreateProjectError = (ErrorResponse | HTTPValidationError);

export type ReadProjectData = {
    path: {
        id: number;
    };
};

export type ReadProjectResponse = (ProjectPublicOut);

export type ReadProjectError = (ErrorResponse | HTTPValidationError);

export type UpdateProjectData = {
    body: ProjectUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProjectResponse = (ProjectPublicOut);

export type UpdateProjectError = (ErrorResponse | HTTPValidationError);

export type DeleteProjectData = {
    path: {
        id: number;
    };
};

export type DeleteProjectResponse = (Message);

export type DeleteProjectError = (ErrorResponse | HTTPValidationError);

export type ReadProjectTypesResponse = (ProjectTypesPublicOut);

export type ReadProjectTypesError = (ErrorResponse);

export type CreateProjectTypeData = {
    body: ProjectTypeCreateIn;
};

export type CreateProjectTypeResponse = (ProjectTypePublicOut);

export type CreateProjectTypeError = (ErrorResponse | HTTPValidationError);

export type GetProjectTypeByIdData = {
    path: {
        id: number;
    };
};

export type GetProjectTypeByIdResponse = (ProjectTypePublicOut);

export type GetProjectTypeByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateProjectTypeData = {
    body: ProjectTypeUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProjectTypeResponse = (ProjectTypePublicOut);

export type UpdateProjectTypeError = (ErrorResponse | HTTPValidationError);

export type ReadBuildingTypesResponse = (BuildingTypesPublicOut);

export type ReadBuildingTypesError = (ErrorResponse);

export type CreateBuildingTypeData = {
    body: BuildingTypeCreateIn;
};

export type CreateBuildingTypeResponse = (BuildingTypePublicOut);

export type CreateBuildingTypeError = (ErrorResponse | HTTPValidationError);

export type GetBuildingTypeByIdData = {
    path: {
        id: number;
    };
};

export type GetBuildingTypeByIdResponse = (BuildingTypePublicOut);

export type GetBuildingTypeByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateBuildingTypeData = {
    body: BuildingTypeUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateBuildingTypeResponse = (BuildingTypePublicOut);

export type UpdateBuildingTypeError = (ErrorResponse | HTTPValidationError);

export type ReadProjectTaskTypesResponse = (ProjectTaskTypesPublicOut);

export type ReadProjectTaskTypesError = (ErrorResponse);

export type CreateProjectTaskTypeData = {
    body: ProjectTaskTypeCreateIn;
};

export type CreateProjectTaskTypeResponse = (ProjectTaskTypePublicOut);

export type CreateProjectTaskTypeError = (ErrorResponse | HTTPValidationError);

export type GetProjectTaskTypeByIdData = {
    path: {
        id: number;
    };
};

export type GetProjectTaskTypeByIdResponse = (ProjectTaskTypePublicOut);

export type GetProjectTaskTypeByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateProjectTaskTypeData = {
    body: ProjectTaskTypeUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProjectTaskTypeResponse = (ProjectTaskTypePublicOut);

export type UpdateProjectTaskTypeError = (ErrorResponse | HTTPValidationError);

export type ReadProjectClassesResponse = (ProjectClassesPublicOut);

export type ReadProjectClassesError = (ErrorResponse);

export type CreateProjectClassData = {
    body: ProjectClassCreateIn;
};

export type CreateProjectClassResponse = (ProjectClassPublicOut);

export type CreateProjectClassError = (ErrorResponse | HTTPValidationError);

export type GetProjectClassByIdData = {
    path: {
        id: number;
    };
};

export type GetProjectClassByIdResponse = (ProjectClassPublicOut);

export type GetProjectClassByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateProjectClassData = {
    body: ProjectClassUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProjectClassResponse = (ProjectClassPublicOut);

export type UpdateProjectClassError = (ErrorResponse | HTTPValidationError);

export type ReadBuildingStructureTypesResponse = (BuildingStructureTypesPublicOut);

export type ReadBuildingStructureTypesError = (ErrorResponse);

export type CreateBuildingStructureTypeData = {
    body: BuildingStructureTypeCreateIn;
};

export type CreateBuildingStructureTypeResponse = (BuildingStructureTypePublicOut);

export type CreateBuildingStructureTypeError = (ErrorResponse | HTTPValidationError);

export type GetBuildingStructureTypeByIdData = {
    path: {
        id: number;
    };
};

export type GetBuildingStructureTypeByIdResponse = (BuildingStructureTypePublicOut);

export type GetBuildingStructureTypeByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateBuildingStructureTypeData = {
    body: BuildingStructureTypeUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateBuildingStructureTypeResponse = (BuildingStructureTypePublicOut);

export type UpdateBuildingStructureTypeError = (ErrorResponse | HTTPValidationError);

export type ReadProjectRateAdjustmentClassesResponse = (ProjectRateAdjustmentClassesPublicOut);

export type ReadProjectRateAdjustmentClassesError = (ErrorResponse);

export type CreateProjectRateAdjustmentClassData = {
    body: ProjectRateAdjustmentClassCreateIn;
};

export type CreateProjectRateAdjustmentClassResponse = (ProjectRateAdjustmentClassPublicOut);

export type CreateProjectRateAdjustmentClassError = (ErrorResponse | HTTPValidationError);

export type GetProjectRateAdjustmentClassByIdData = {
    path: {
        id: number;
    };
};

export type GetProjectRateAdjustmentClassByIdResponse = (ProjectRateAdjustmentClassPublicOut);

export type GetProjectRateAdjustmentClassByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateProjectRateAdjustmentClassData = {
    body: ProjectRateAdjustmentClassUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProjectRateAdjustmentClassResponse = (ProjectRateAdjustmentClassPublicOut);

export type UpdateProjectRateAdjustmentClassError = (ErrorResponse | HTTPValidationError);

export type ReadQualityRatioClassesResponse = (QualityRatioClassesPublicOut);

export type ReadQualityRatioClassesError = (ErrorResponse);

export type CreateQualityRaitioClassData = {
    body: QualityRatioClassCreateIn;
};

export type CreateQualityRaitioClassResponse = (QualityRatioClassPublicOut);

export type CreateQualityRaitioClassError = (ErrorResponse | HTTPValidationError);

export type GetQualityRaitioClassByIdData = {
    path: {
        id: number;
    };
};

export type GetQualityRaitioClassByIdResponse = (QualityRatioClassPublicOut);

export type GetQualityRaitioClassByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateQualityRaitioClassData = {
    body: QualityRatioClassUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateQualityRaitioClassResponse = (QualityRatioClassPublicOut);

export type UpdateQualityRaitioClassError = (ErrorResponse | HTTPValidationError);

export type ReadProdValueCalcRatiosDefaultResponse = (ProdValueCalcRatioPublicOut);

export type ReadProdValueCalcRatiosDefaultError = (ErrorResponse);

export type ReadProdValueCalcRatiosResponse = (ProdValueCalcRatiosPublicOut);

export type ReadProdValueCalcRatiosError = (ErrorResponse);

export type CreateProdValueCalcRatioData = {
    body: ProdValueCalcRatioCreateIn;
};

export type CreateProdValueCalcRatioResponse = (ProdValueCalcRatioPublicOut);

export type CreateProdValueCalcRatioError = (ErrorResponse | HTTPValidationError);

export type GetProdValueCalcRatioByIdData = {
    path: {
        id: number;
    };
};

export type GetProdValueCalcRatioByIdResponse = (ProdValueCalcRatioPublicOut);

export type GetProdValueCalcRatioByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateProdValueCalcRatioData = {
    body: ProdValueCalcRatioUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProdValueCalcRatioResponse = (ProdValueCalcRatioPublicOut);

export type UpdateProdValueCalcRatioError = (ErrorResponse | HTTPValidationError);

export type DeleteProdValueCalcRatioData = {
    path: {
        id: number;
    };
};

export type DeleteProdValueCalcRatioResponse = (unknown);

export type DeleteProdValueCalcRatioError = (ErrorResponse | HTTPValidationError);

export type ReadJobPayoutRatioProfilesData = {
    query?: {
        hidden?: boolean;
    };
};

export type ReadJobPayoutRatioProfilesResponse = (JobPayoutRatioProfilesPublicOut);

export type ReadJobPayoutRatioProfilesError = (ErrorResponse | HTTPValidationError);

export type CreateJobPayoutRatioProfileData = {
    body: JobPayoutRatioProfileCreateIn;
};

export type CreateJobPayoutRatioProfileResponse = (JobPayoutRatioProfilePublicOut);

export type CreateJobPayoutRatioProfileError = (ErrorResponse | HTTPValidationError);

export type GetJobPayoutRatioProfileByIdData = {
    path: {
        id: number;
    };
};

export type GetJobPayoutRatioProfileByIdResponse = (JobPayoutRatioProfilePublicOut);

export type GetJobPayoutRatioProfileByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateJobPayoutRatioProfileData = {
    body: JobPayoutRatioProfileUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateJobPayoutRatioProfileResponse = (JobPayoutRatioProfilePublicOut);

export type UpdateJobPayoutRatioProfileError = (ErrorResponse | HTTPValidationError);

export type ReadDepartmentPayoutRatiosResponse = (DepartmentPayoutRatiosPublicOut);

export type ReadDepartmentPayoutRatiosError = (ErrorResponse);

export type GetDepartmentPayoutRatioByIdData = {
    path: {
        id: number;
    };
};

export type GetDepartmentPayoutRatioByIdResponse = (DepartmentPayoutRatioPublicOut);

export type GetDepartmentPayoutRatioByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateDepartmentPayoutRatioByIdData = {
    body: DepartmentPayoutRatioUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateDepartmentPayoutRatioByIdResponse = (DepartmentPayoutRatioPublicOut);

export type UpdateDepartmentPayoutRatioByIdError = (ErrorResponse | HTTPValidationError);

export type ReadDepartmentPayoutRatiosByProjectClassIdData = {
    path: {
        project_class_id: number;
    };
};

export type ReadDepartmentPayoutRatiosByProjectClassIdResponse = (DepartmentPayoutRatiosPublicOut);

export type ReadDepartmentPayoutRatiosByProjectClassIdError = (ErrorResponse | HTTPValidationError);

export type GetDepartmentPayoutRatioData = {
    path: {
        project_class_id: number;
        project_rate_adjustment_class_id: number;
    };
};

export type GetDepartmentPayoutRatioResponse = (DepartmentPayoutRatioPublicOut);

export type GetDepartmentPayoutRatioError = (ErrorResponse | HTTPValidationError);

export type UpdateDepartmentPayoutRatioByComboData = {
    body: DepartmentPayoutRatioUpdateIn;
    path: {
        project_class_id: number;
        project_rate_adjustment_class_id: number;
    };
};

export type UpdateDepartmentPayoutRatioByComboResponse = (DepartmentPayoutRatioPublicOut);

export type UpdateDepartmentPayoutRatioByComboError = (ErrorResponse | HTTPValidationError);

export type ReadEmployeesData = {
    query?: {
        limit?: number;
        show_disabled?: (boolean | null);
        skip?: number;
    };
};

export type ReadEmployeesResponse = (EmployeesPublicOut);

export type ReadEmployeesError = (ErrorResponse | HTTPValidationError);

export type CreateEmployeeData = {
    body: EmployeeCreateIn;
};

export type CreateEmployeeResponse = (EmployeePublicOut);

export type CreateEmployeeError = (ErrorResponse | HTTPValidationError);

export type SearchEmployeeData = {
    path: {
        query: string;
    };
    query?: {
        department_id?: (number | null);
        limit?: number;
        skip?: number;
    };
};

export type SearchEmployeeResponse = (EmployeesPublicOut);

export type SearchEmployeeError = (ErrorResponse | HTTPValidationError);

export type ReadEmployeesByDepartmentData = {
    path: {
        id: number;
    };
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadEmployeesByDepartmentResponse = (EmployeesPublicOut);

export type ReadEmployeesByDepartmentError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeByIdData = {
    path: {
        id: number;
    };
};

export type GetEmployeeByIdResponse = (EmployeePublicOut);

export type GetEmployeeByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateEmployeeData = {
    body: EmployeeUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateEmployeeResponse = (EmployeePublicOut);

export type UpdateEmployeeError = (ErrorResponse);

export type GetEmployeeReportByIdData = {
    path: {
        id: number;
    };
};

export type GetEmployeeReportByIdResponse = (unknown);

export type GetEmployeeReportByIdError = (ErrorResponse | HTTPValidationError);

export type GeneratePinyinResponse = (Message);

export type GeneratePinyinError = (ErrorResponse);

export type ReadDepartmentsResponse = (DepartmentsPublicOut);

export type ReadDepartmentsError = (ErrorResponse);

export type GetDepartmentByIdData = {
    path: {
        id: number;
    };
};

export type GetDepartmentByIdResponse = (DepartmentPublicOut);

export type GetDepartmentByIdError = (ErrorResponse | HTTPValidationError);

export type ReadWorkLocationsResponse = (WorkLocationsPublicOut);

export type ReadWorkLocationsError = (ErrorResponse);

export type CreateWorkLocationData = {
    body: WorkLocationCreateIn;
};

export type CreateWorkLocationResponse = (WorkLocationPublicOut);

export type CreateWorkLocationError = (ErrorResponse | HTTPValidationError);

export type GetWorkLocationByIdData = {
    path: {
        id: number;
    };
};

export type GetWorkLocationByIdResponse = (WorkLocationPublicOut);

export type GetWorkLocationByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateWorkLocationData = {
    body: WorkLocationUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateWorkLocationResponse = (WorkLocationPublicOut);

export type UpdateWorkLocationError = (ErrorResponse | HTTPValidationError);

export type ReadEmployeeTitlesResponse = (EmployeeTitlesPublicOut);

export type ReadEmployeeTitlesError = (ErrorResponse);

export type CreateEmployeeTitleData = {
    body: EmployeeTitleCreateIn;
};

export type CreateEmployeeTitleResponse = (EmployeeTitlePublicOut);

export type CreateEmployeeTitleError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeTitleByIdData = {
    path: {
        id: number;
    };
};

export type GetEmployeeTitleByIdResponse = (EmployeeTitlePublicOut);

export type GetEmployeeTitleByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateEmployeeTitleData = {
    body: EmployeeTitleUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateEmployeeTitleResponse = (EmployeeTitlePublicOut);

export type UpdateEmployeeTitleError = (ErrorResponse | HTTPValidationError);

export type ReadProfessionalTitlesResponse = (ProfessionalTitlesPublicOut);

export type ReadProfessionalTitlesError = (ErrorResponse);

export type CreateProfessionalTitleData = {
    body: ProfessionalTitleCreateIn;
};

export type CreateProfessionalTitleResponse = (ProfessionalTitlePublicOut);

export type CreateProfessionalTitleError = (ErrorResponse | HTTPValidationError);

export type GetProfessionalTitleByIdData = {
    path: {
        id: number;
    };
};

export type GetProfessionalTitleByIdResponse = (ProfessionalTitlePublicOut);

export type GetProfessionalTitleByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateProfessionalTitleData = {
    body: ProfessionalTitleUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProfessionalTitleResponse = (ProfessionalTitlePublicOut);

export type UpdateProfessionalTitleError = (ErrorResponse | HTTPValidationError);

export type ReadEmployeeStatusesResponse = (EmployStatusesPublicOut);

export type ReadEmployeeStatusesError = (ErrorResponse);

export type CreateEmployeeStatusData = {
    body: EmployStatusCreateIn;
};

export type CreateEmployeeStatusResponse = (EmployStatusPublicOut);

export type CreateEmployeeStatusError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeStatusByIdData = {
    path: {
        id: number;
    };
};

export type GetEmployeeStatusByIdResponse = (EmployStatusPublicOut);

export type GetEmployeeStatusByIdError = (ErrorResponse | HTTPValidationError);

export type UpdateEmployeeStatusData = {
    body: EmployStatusUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateEmployeeStatusResponse = (EmployStatusPublicOut);

export type UpdateEmployeeStatusError = (ErrorResponse | HTTPValidationError);

export type GetProjectPayoutData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type GetProjectPayoutResponse = (ProjectPayoutsPublicOut);

export type GetProjectPayoutError = (ErrorResponse | HTTPValidationError);

export type CreateProjectPayoutData = {
    body: ProjectPayoutCreateIn;
};

export type CreateProjectPayoutResponse = (ProjectPayoutPublicOut);

export type CreateProjectPayoutError = (ErrorResponse | HTTPValidationError);

export type GetProjectPayoutByProjectIdData = {
    path: {
        id: number;
    };
};

export type GetProjectPayoutByProjectIdResponse = (ProjectPayoutPublicOut);

export type GetProjectPayoutByProjectIdError = (ErrorResponse | HTTPValidationError);

export type ReadProjectPayoutData = {
    path: {
        id: number;
    };
};

export type ReadProjectPayoutResponse = (ProjectPayoutPublicOut);

export type ReadProjectPayoutError = (ErrorResponse | HTTPValidationError);

export type UpdateProjectPayoutData = {
    body: ProjectPayoutUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateProjectPayoutResponse = (ProjectPayoutPublicOut);

export type UpdateProjectPayoutError = (ErrorResponse | HTTPValidationError);

export type GetContractPaymentResponse = (ContractPaymentsPublicOut);

export type GetContractPaymentError = (ErrorResponse);

export type CreateContractPaymentData = {
    body: ContractPaymentCreateIn;
};

export type CreateContractPaymentResponse = (ContractPaymentPublicOut);

export type CreateContractPaymentError = (ErrorResponse | HTTPValidationError);

export type GetContractPaymentByProjectPayoutIdData = {
    path: {
        id: number;
    };
};

export type GetContractPaymentByProjectPayoutIdResponse = (ContractPaymentsPublicOut);

export type GetContractPaymentByProjectPayoutIdError = (ErrorResponse | HTTPValidationError);

export type GetContractPaymentByProjectIdData = {
    path: {
        id: number;
    };
};

export type GetContractPaymentByProjectIdResponse = (ContractPaymentPublicOut);

export type GetContractPaymentByProjectIdError = (ErrorResponse | HTTPValidationError);

export type ReadContractPaymentData = {
    path: {
        id: number;
    };
};

export type ReadContractPaymentResponse = (ContractPaymentPublicOut);

export type ReadContractPaymentError = (ErrorResponse | HTTPValidationError);

export type UpdateContractPaymentData = {
    body: ContractPaymentUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateContractPaymentResponse = (ContractPaymentPublicOut);

export type UpdateContractPaymentError = (ErrorResponse | HTTPValidationError);

export type DeleteContractPaymentData = {
    path: {
        id: number;
    };
};

export type DeleteContractPaymentResponse = (Message);

export type DeleteContractPaymentError = (ErrorResponse | HTTPValidationError);

export type GetProjectListReportData = {
    query?: {
        project_year?: (number | null);
    };
};

export type GetProjectListReportResponse = (string);

export type GetProjectListReportError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeListReportResponse = (string);

export type GetEmployeeListReportError = (ErrorResponse);

export type GetContractPaymentListReportData = {
    query?: {
        project_id?: (number | null);
        time_end?: (string | null);
        time_start?: (string | null);
    };
};

export type GetContractPaymentListReportResponse = (string);

export type GetContractPaymentListReportError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeProjectPayoutListByPaymentYearReportData = {
    query: {
        employee_id: number;
        payment_year: number;
    };
};

export type GetEmployeeProjectPayoutListByPaymentYearReportResponse = (string);

export type GetEmployeeProjectPayoutListByPaymentYearReportError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeProjectPayoutListByProjectYearReportData = {
    query: {
        employee_id: number;
        project_year: number;
    };
};

export type GetEmployeeProjectPayoutListByProjectYearReportResponse = (string);

export type GetEmployeeProjectPayoutListByProjectYearReportError = (ErrorResponse | HTTPValidationError);

export type GetEmployeeProjectProductionValueByProjectYearReportData = {
    query: {
        employee_id: number;
        project_year: number;
    };
};

export type GetEmployeeProjectProductionValueByProjectYearReportResponse = (string);

export type GetEmployeeProjectProductionValueByProjectYearReportError = (ErrorResponse | HTTPValidationError);

export type GetCompanyProjectPayoutListByPaymentYearReportData = {
    query: {
        payment_year: number;
    };
};

export type GetCompanyProjectPayoutListByPaymentYearReportResponse = (string);

export type GetCompanyProjectPayoutListByPaymentYearReportError = (ErrorResponse | HTTPValidationError);

export type GetCompanyProjectPayoutListByProjectYearReportData = {
    query: {
        project_year: number;
    };
};

export type GetCompanyProjectPayoutListByProjectYearReportResponse = (string);

export type GetCompanyProjectPayoutListByProjectYearReportError = (ErrorResponse | HTTPValidationError);

export type GetCompanyProjectProductionValueByProjectYearReportData = {
    query: {
        project_year: number;
    };
};

export type GetCompanyProjectProductionValueByProjectYearReportResponse = (string);

export type GetCompanyProjectProductionValueByProjectYearReportError = (ErrorResponse | HTTPValidationError);

export type GetProjectPayoutListByPaymentYearReportData = {
    query: {
        payment_year: number;
        project_id: number;
    };
};

export type GetProjectPayoutListByPaymentYearReportResponse = (string);

export type GetProjectPayoutListByPaymentYearReportError = (ErrorResponse | HTTPValidationError);

export type GetProjectPayoutListByProjectYearReportData = {
    query: {
        project_id: number;
    };
};

export type GetProjectPayoutListByProjectYearReportResponse = (string);

export type GetProjectPayoutListByProjectYearReportError = (ErrorResponse | HTTPValidationError);

export type GetProjectProductionValueReportData = {
    query: {
        project_id: number;
    };
};

export type GetProjectProductionValueReportResponse = (string);

export type GetProjectProductionValueReportError = (ErrorResponse | HTTPValidationError);

export type GetProjectPayoutReportData = {
    query: {
        project_id: number;
    };
};

export type GetProjectPayoutReportResponse = (string);

export type GetProjectPayoutReportError = (ErrorResponse | HTTPValidationError);

export type GetContractPaymentPayoutListReportData = {
    query: {
        contract_payment_id: number;
    };
};

export type GetContractPaymentPayoutListReportResponse = (string);

export type GetContractPaymentPayoutListReportError = (ErrorResponse | HTTPValidationError);

export type TestEmailData = {
    query: {
        email_to: string;
    };
};

export type TestEmailResponse = (Message);

export type TestEmailError = (HTTPValidationError);

export type HealthCheckResponse = (boolean);

export type HealthCheckError = unknown;

export type ReadItemsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadItemsResponse = (ItemsPublicOut);

export type ReadItemsError = (HTTPValidationError);

export type CreateItemData = {
    body: ItemCreateIn;
};

export type CreateItemResponse = (ItemPublicOut);

export type CreateItemError = (HTTPValidationError);

export type ReadItemData = {
    path: {
        id: number;
    };
};

export type ReadItemResponse = (ItemPublicOut);

export type ReadItemError = (HTTPValidationError);

export type UpdateItemData = {
    body: ItemUpdateIn;
    path: {
        id: number;
    };
};

export type UpdateItemResponse = (ItemPublicOut);

export type UpdateItemError = (HTTPValidationError);

export type DeleteItemData = {
    path: {
        id: number;
    };
};

export type DeleteItemResponse = (Message);

export type DeleteItemError = (HTTPValidationError);